<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Nombre: Kamal
Curso: 1ºDAM
Fecha: 3/04/2025 
Ejercicio 6
-->

<!DOCTYPE paises [
  <!ELEMENT paises (pais*)>
<!ELEMENT pais (nombre, unionEuropea?, otan?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT unionEuropea EMPTY>
<!ELEMENT otan EMPTY>
]>

<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea/>
        <otan/>
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan/>
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea/>
    </pais>

</paises>