=== k7054/Lenguaje-de-marcas/Validación XML - DTD II/Ejercicio 2/EquiposNBA.dtd
<!-- 
Nombre: Kamal
Curso: 1ยบ DAM 
Fecha: 3/04/2025 
Ejercicio 2
-->

<!ELEMENT EquiposNBA (equipo | nombre)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT equipo (titulos, posicion, quinteto)>
<!ATTLIST equipo conferencia CDATA #REQUIRED>
<!ELEMENT titulos (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT quinteto (#PCDATA)>

=== k7054/Lenguaje-de-marcas/Validación XML - DTD II/Ejercicio 2/Ejercicio 2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Nombre: Kamal
Curso: 1ยบ DAM 
Fecha: 3/04/2025 
Ejercicio 2
-->

<!DOCTYPE EquiposNBA SYSTEM "EquiposNBA.dtd">

<EquiposNBA>
    <nombre>Los Angeles Lakers</nombre>
    <equipo conferencia="oeste">
        <titulos>17</titulos>
        <posicion>1</posicion>
        <quinteto>LeBron James, Anthony Davis, D'Angelo Russell, Austin Reaves, Rui Hachimura</quinteto>
    </equipo>
    
    <nombre>Boston Celtics</nombre>
    <equipo conferencia="este">
        <titulos>17</titulos>
        <posicion>2</posicion>
        <quinteto>Jayson Tatum, Jaylen Brown, Marcus Smart, Al Horford, Robert Williams</quinteto>
    </equipo>
    
    <nombre>Golden State Warriors</nombre>
    <equipo conferencia="oeste">
        <titulos>7</titulos>
        <posicion>3</posicion>
        <quinteto>Stephen Curry, Klay Thompson, Draymond Green, Andrew Wiggins, Kevon Looney</quinteto>
    </equipo>
</EquiposNBA>
