=== k7054/Lenguaje-de-marcas/Validación XML - DTD II/Ejercicio 3/panel.dtd
<!ELEMENT panel (aeropuerto, vuelo+)>
<!ATTLIST panel fecha CDATA #REQUIRED>

<!ELEMENT aeropuerto (#PCDATA)>

<!ELEMENT vuelo (diario?, origen, destino, hora-salida, hora-llegada)>
<!ATTLIST vuelo 
    codigo ID #REQUIRED
    estado (C | E | R) "E">

<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora-salida (#PCDATA)>
<!ELEMENT hora-llegada (#PCDATA)>

=== k7054/Lenguaje-de-marcas/Validación XML - DTD II/Ejercicio 3/Ejercicio 3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Nombre: Kamal
Curso: 1ยบ DAM 
Fecha: 3/04/2025 
Ejercicio 3
-->

<!DOCTYPE panel SYSTEM "panel.dtd">

<panel fecha="2025-04-03">
    <aeropuerto>JFK International Airport</aeropuerto>
    <vuelo codigo="V22" estado="R">
        <diario/>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora-salida>9:30</hora-salida>
        <hora-llegada>11:30</hora-llegada>
    </vuelo>
    <vuelo codigo="V23" estado="C">
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora-salida>10:15</hora-salida>
        <hora-llegada>11:15</hora-llegada>
    </vuelo>
</panel>
