<?xml version="1.0" encoding="UTF-8"?>

<!-- 
Nombre: Kamal
Curso: 1ºDAM
Fecha: 3/04/2025 
Ejercicio 3
-->

<!DOCTYPE aeropuertos [
  <!ELEMENT aeropuertos (aeropuerto*)>
<!ELEMENT aeropuerto (nombre, cerrado?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cerrado (#PCDATA)>
]>

<aeropuertos>
    <aeropuerto>
        <nombre>Berlin Schönefeld (SFX)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlin Tempelhof (THF)</nombre>
        <cerrado>2008</cerrado>
    </aeropuerto>
</aeropuertos>